name: "Build"

on:
  pull_request:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  release:
    types:
      - released

permissions:
  actions: write
  contents: read
  id-token: write

concurrency:
  cancel-in-progress: true
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "git / checkout"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6.0.1

      - name: "java / setup"
        uses: "actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654" # v5.2.0
        with:
          check-latest: true
          distribution: "zulu"
          java-version: "17"

      - name: "gradle / setup"
        uses: "gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2" # v5.0.0

      - name: "gradle / build"
        run: "./gradlew build"

      - name: "gradle / resolve metadata"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "VERSION_TYPE=SNAPSHOT" >> $GITHUB_ENV
          else
            echo "VERSION_TYPE=RELEASE" >> $GITHUB_ENV
          fi

      - name: "gradle / publish snapshot"
        if: "${{ runner.os == 'Linux' && env.VERSION_TYPE == 'SNAPSHOT' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
        run: "./gradlew publish"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"

      - name: "gradle / publish release"
        if: "${{ runner.os == 'Linux' && env.VERSION_TYPE == 'RELEASE' && github.event_name == 'release' }}"
        run: "./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository"
        env:
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.SONATYPE_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.SONATYPE_SIGNING_PASSWORD }}"
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
